spring.application.name=peliculas


spring.datasource.url=jdbc:oracle:thin:@j5q4b1nob2t8v68g_high?TNS_ADMIN=/app/wallet
spring.datasource.username=fullstack1
spring.datasource.password=Holaquetal123@
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000